[package]
name = "combine-jpeg"
version = "0.1.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.13"
log = "*"
combine = { version = "4.0.0-alpha.1", path = "../combine" }

[dev-dependencies]
env_logger = "*"
huffman-compress = "0.6"
